# Generated by Django 3.1 on 2020-12-20 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partidos.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_url', models.CharField(editable=False, max_length=50)),
                ('slogan', models.TextField()),
                ('favicon', stdimage.models.StdImageField(upload_to=partidos.models.favicon_dir)),
                ('qtd_votos', models.ManyToManyField(blank=True, default=None, related_name='qtd_votos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('voto', 'voto'), ('unVoto', 'unVoto')], default='unVoto', max_length=7)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos.partido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
